blank_issues_enabled: false
contact_links:
  - name: General Issue
    url: https://github.com/official-Cromatin/Post-It/issues/new?assignees=&labels=&template=general_issue.yml
    about: Nothing is matching your needs? Create an Normal issue