name: Issue Report
description: You found a bug or something does not work as it should, report it here
labels: ["feature-request"]
body:
  - type: markdown
    attributes:
      value: "*Before you create an issue, please look first if an issue already exists that your concern is treated*"

  - type: textarea
    attributes:
      label: Issue description
      description: A detailed description of the feature you request. The more descriptive you are, the more likely the implementation will satisfy you
    validations:
      required: true
