name: Code Analysis (Bandit)

on: push
jobs:
  bandit:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: mdegis/bandit-action@v1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: "src/"
          level: high
          confidence: high
          exit_zero: true
