name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 1'

permissions:
  contents: read
  pull-requests: write

jobs:
  renovate:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Renovate
        run: npm install -g renovate

      - name: Run Renovate
        env:
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: debug
        run: |
          cd ${{ github.workspace }}
          renovate --platform=github
